# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_num', models.CharField(max_length=18, unique=True)),
                ('sex', models.BooleanField(choices=[('1', '\u7537'), ('0', '\u5973')])),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_created=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
