# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadrecord',
            old_name='file',
            new_name='excel_file',
        ),
    ]
