# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190323_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='create_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 23, 23, 9, 23, 568836)),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.BooleanField(choices=[(True, '\u7537'), (False, '\u5973')]),
        ),
    ]
