# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190323_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_time',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_num',
            field=models.CharField(max_length=18),
        ),
    ]
